device: cuda:0
model_name: gemma2
steering_matrix_path: data/steering_matrix/gemma2/steering_matrix.pt
input_file: data/instructions/test/gemma2/aim_gemma2.json
output_file: data/responses/gemma2/aim_gemma2_results.json
batch_size: 32
max_new_tokens: 128
file_rename: False
prompt_column: query
response_column: output
strength: -0.02,-0.04,-0.06,-0.08,-0.10,-0.12,-0.14